name: Tests
on: [push]
concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true
jobs:
  testes:
    name: Run Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        ruby: [ '2.7' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle Install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Run RSpec
      run: bundle exec rspec -f j -o tmp/rspec_results.json -f p

    - name: RSpec Report
      uses: SonicGarden/rspec-report-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        json-path: tmp/rspec_results.json
      if: always()
